openai_api_key: ${openai-api-key}
connections:
  - name: tw_campaign_finance
    databaseName: tw_campaign_finance
    schemaName: main
    dbType: duckdb
    url: >-
      jdbc:duckdb:/Users/jasir/rosetta-dbt-studio-projects/tw_campaign_finance/tw_campaign_finance.duckdb
