name: "CI"
jobs:
  - name: "run-dbt"
    steps:
      - name: Run dbt
        plugin: dbt@v1
        command: dbt seed && dbt run
  - name: "teardown"
    type: "cleanup"
    steps:
      - name: Run teardown
        plugin: command@v1
        command: echo "TEARDOWN"
